"use client";
import Link from "next/link";
import { useAzumi } from "@/components/azumi-provider";
import { Badge, PageHeading } from "@/components/ui";
import { dayKey, money } from "@/lib/azumi-client";
import { OrdersTable } from "./orders";

export function DashboardScreen() {
  const { snapshot, catalog } = useAzumi(), orders = snapshot?.adminOrders || [], now = new Date(snapshot!.serverTime), today = dayKey(now);
  const todayOrders = orders.filter(o => dayKey(new Date(o.date)) === today && o.status !== "Cancelado"), sales = todayOrders.reduce((sum, o) => sum + o.totals.total, 0);
  const counts = new Map<string, number>(); orders.filter(o => o.status !== "Cancelado").forEach(o => o.items.forEach(i => counts.set(i.name, (counts.get(i.name) || 0) + i.qty)));
  const dates = Array.from({ length: 7 }, (_, i) => { const date = new Date(now.getTime() - (6 - i) * 86400000); const total = orders.filter(o => dayKey(new Date(o.date)) === dayKey(date) && o.status !== "Cancelado").reduce((sum, o) => sum + o.totals.total, 0); return { date, total }; });
  const max = Math.max(1, ...dates.map(d => d.total));
  return <><PageHeading title="Todo bajo control." eyebrow="Azumi · San Francisco" /><p className="muted">Un buen servicio empieza por una buena experiencia.</p><div className="metrics">{[["Ventas de hoy", money(sales), "Pedidos registrados"], ["Pedidos", todayOrders.length, "Hoy"], ["Ticket promedio", money(todayOrders.length ? sales / todayOrders.length : 0), "Por pedido"], ["Clientes", new Set(orders.map(o => o.customer.phone)).size, "Clientes registrados"]].map(([label, value, hint]) => <section className="card metric" key={label}><small>{label}</small><strong>{value}</strong><small>{hint}</small></section>)}</div><div className="two-col"><section className="card"><div className="flex"><h3>Ventas de los últimos 7 días</h3><Badge>Pedidos registrados</Badge></div><div className="chart" aria-label="Ventas de los últimos siete días">{dates.map(({ date, total }) => <div className="chart-column" key={dayKey(date)}><span className="chart-value">{money(total)}</span><div className="bar" style={{ height: `${Math.max(3, total / max * 135)}px` }} /><span>{new Intl.DateTimeFormat("es-PA", { timeZone: "America/Panama", weekday: "short" }).format(date)}</span></div>)}</div></section><section className="card"><h3>Actividad del restaurante</h3><div className="total-row"><span>Pedidos pendientes</span><strong>{orders.filter(o => ["Recibido", "Confirmado"].includes(o.status)).length}</strong></div><div className="total-row"><span>Completados</span><strong>{orders.filter(o => o.status === "Entregado").length}</strong></div><div className="total-row"><span>Zonas activas</span><strong>{catalog.zones.filter(z => z.active && z.type === "allowed").length}</strong></div><Link href="/admin/delivery" className="button secondary">Administrar delivery</Link></section></div><section className="card"><div className="section-heading"><h3>Pedidos recientes</h3><Link href="/admin/pedidos">Ver todos →</Link></div><OrdersTable orders={orders.slice(-5)} /></section><section className="card"><h3>Productos más vendidos</h3>{[...counts].sort((a, b) => b[1] - a[1]).slice(0, 3).map(([name, qty]) => <div className="total-row" key={name}><span>{name}</span><strong>{qty} unidades</strong></div>)}{!counts.size && <p className="muted">Se actualizará cuando recibas pedidos.</p>}</section></>;
}
