"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useAzumi } from "@/components/azumi-provider";
import { Badge, Button, Field, Notice, PageHeading, Select } from "@/components/ui";
import { DeliveryMap } from "@/components/delivery-map";
import { money } from "@/lib/azumi-client";
import type { Point, Zone } from "@/lib/azumi-types";

export function DeliveryScreen() {
  const { catalog } = useAzumi(), [selected, setSelected] = useState(catalog.zones[0]?.id);
  return <><div className="section-heading"><PageHeading title="Zonas de delivery" eyebrow="Hasta donde llega el sabor" /><Link className="button small" href="/admin/delivery/nuevo">+ Crear zona</Link></div><Notice>Las restricciones tienen prioridad sobre las zonas permitidas. Revisa los límites heredados y la posición de referencia del restaurante antes de habilitar el delivery.</Notice><div className="two-col"><section className="card"><DeliveryMap zones={catalog.zones} selected={selected} onSelectZone={setSelected} /><div className="chips"><Badge>Verde · delivery permitido</Badge><Badge coral>Coral · área restringida</Badge></div></section><section className="card"><h3>Cobertura del restaurante</h3><p className="muted">Define tarifas, pedidos mínimos y tiempos de entrega.</p>{catalog.zones.map(zone => <article className={`zone-item ${selected === zone.id ? "selected" : ""}`} key={zone.id}><button className="zone-select" onClick={() => setSelected(zone.id)}><strong>{zone.name}</strong><Badge coral={!zone.active}>{zone.active ? "Activa" : "Pausada"}</Badge></button><p className="helper-text">{zone.type === "restricted" ? "Zona restringida" : `${money(zone.fee)} · mínimo ${money(zone.min)} · ${zone.minutesMin}–${zone.minutesMax} min`}</p><Link className="link-button" href={`/admin/delivery/${zone.id}`}>Editar zona y polígono →</Link></article>)}</section></div></>;
}
const newZone: Zone = { id: "", name: "", type: "allowed", fee: 2, min: 10, minutesMin: 25, minutesMax: 35, priority: 1, active: true, points: [], coordinateSystem: "wgs84" };
export function ZoneEditorScreen({ id }: { id: string }) {
  const { catalog, snapshot } = useAzumi(), zone = catalog.zones.find(z => z.id === id);
  if (!zone && id !== "nuevo") return <><PageHeading title="Zona no encontrada" /><Link href="/admin/delivery">Volver a cobertura</Link></>;
  return <ZoneEditor key={`${id}-${snapshot?.revision}`} initial={zone || newZone} />;
}
function ZoneEditor({ initial }: { initial: Zone }) {
  const { catalog, snapshot, busy, run, saveCatalog, notify } = useAzumi(), router = useRouter();
  const [zone, setZone] = useState(initial), [points, setPoints] = useState<Point[]>(initial.points), [revision] = useState(snapshot?.revision);
  const numeric = (key: "fee" | "min" | "minutesMin" | "minutesMax" | "priority", label: string) => <Field label={label} type="number" min={0} max={key.includes("minutes") ? 240 : undefined} step={key === "fee" || key === "min" ? ".01" : "1"} required value={zone[key]} onChange={e => setZone(z => ({ ...z, [key]: Number(e.target.value) }))} />;
  return <><PageHeading title={initial.id ? "Editar zona" : "Nueva zona"} back="/admin/delivery" /><form data-editing="true" onSubmit={e => { e.preventDefault(); if (points.length < 3) { notify("Dibuja al menos tres puntos."); return; } const updated: Zone = { ...zone, id: zone.id || crypto.randomUUID(), points }; void run(async () => { await saveCatalog({ zones: initial.id ? catalog.zones.map(z => z.id === initial.id ? updated : z) : [...catalog.zones, updated] }, revision); router.push("/admin/delivery"); }); }}><div className="two-col"><section className="card"><DeliveryMap zones={catalog.zones.filter(z => z.id !== initial.id)} vertices={points} onVertices={setPoints} /><p className="helper-text">Haz clic para crear vértices. Arrastra un vértice para modificarlo. El polígono se cierra al guardar.</p><div className="flex"><Button className="ghost small" onClick={() => setPoints(p => p.slice(0, -1))}>Deshacer punto</Button><Button className="ghost small" onClick={() => setPoints([])}>Limpiar</Button><Badge>{points.length} puntos</Badge></div><details className="vertex-list"><summary>Editar coordenadas de los vértices</summary>{points.map((p, index) => <div className="form-grid" key={index}><Field label={`Vértice ${index + 1} · Longitud`} type="number" min={-180} max={180} step="0.000001" value={p[0]} onChange={e => setPoints(values => values.map((value, i) => i === index ? [Number(e.target.value), value[1]] : value))} /><Field label={`Vértice ${index + 1} · Latitud`} type="number" min={-90} max={90} step="0.000001" value={p[1]} onChange={e => setPoints(values => values.map((value, i) => i === index ? [value[0], Number(e.target.value)] : value))} /></div>)}</details></section><section className="card"><h3>Propiedades de la zona</h3><Field label="Nombre" maxLength={120} required value={zone.name} onChange={e => setZone(z => ({ ...z, name: e.target.value }))} /><Select label="Tipo" value={zone.type} onChange={e => setZone(z => ({ ...z, type: e.target.value as Zone["type"] }))}><option value="allowed">Delivery permitido</option><option value="restricted">Zona restringida</option></Select><div className="form-grid">{numeric("fee", "Tarifa ($)")}{numeric("min", "Pedido mínimo ($)")}{numeric("minutesMin", "Tiempo mínimo (min)")}{numeric("minutesMax", "Tiempo máximo (min)")}{numeric("priority", "Prioridad")}</div><label className="choice"><input type="checkbox" checked={zone.active} onChange={e => setZone(z => ({ ...z, active: e.target.checked }))} />Zona activa</label><Button className="spacer" type="submit" disabled={busy}>{busy ? "Guardando…" : "Finalizar y guardar zona"}</Button><Notice>Una zona restringida bloquea cualquier zona de delivery que la cubra.</Notice></section></div></form></>;
}
